# Generated by Django 5.2.8 on 2025-11-14 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo_evento', models.CharField(choices=[('conferencia', 'Conferencia'), ('concierto', 'Concierto'), ('seminario', 'Seminario')], max_length=20, verbose_name='Tipo de Evento')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Evento')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('es_privado', models.BooleanField(default=False, verbose_name='Evento Privado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asistentes', models.ManyToManyField(blank=True, related_name='eventos_asistidos', to=settings.AUTH_USER_MODEL, verbose_name='Asistentes')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
                'permissions': [('puede_gestionar_eventos', 'Puede gestionar todos los eventos'), ('puede_organizar_eventos', 'Puede organizar eventos')],
            },
        ),
    ]
